name: TBGeneral
version: '0.1-BETA'
main: org.TBCreates.TBGeneral.TBGeneral
api-version: '1.21'
load: STARTUP
authors: [ thebestharrison ]
description: A plugin for all your general needs
depend: [LuckPerms]
commands:
  givebook:
    description: Force give the TBGeneral Info book to a player.
    usage: /givebook <player>
    permission: tbgeneral.givebook
    permission-message: You do not have permission to use this command.
  fly:
    description: Toggles flying for command sender.
    usage: /fly
    aliases: f
    permission: TBGeneral.fly
  menu:
    description: Toggles flying for command sender.
    usage: /gmselect
    aliases: gmsel
    permission: TBGeneral.gmselect
permissions:
  tbgeneral.givebook:
    description: Allows forcing the TBGeneral book to be given.
    default: op
